use_frameworks!

platform :ios, '8.0'

target 'LYAlertControllerShower_Example' do
  pod 'LYAlertControllerShower', :path => '../'

  target 'LYAlertControllerShower_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
